### ISSUE TITLE
installation instructions needed

### ISSUE THREAD

**Issue by ggdhines** [ztane/python-Levenshtein#23]
I've done
sudo python setup.py install
but then when I try:
import Levenshtein
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "Levenshtein/__init__.py", line 1, in <module>
    from Levenshtein import _levenshtein
ImportError: cannot import name _levenshtein

In the source directory, I've done
gcc -Wall -I/usr/include/python2.7 -lpython2.7 -c _levenshtein.c
to create a file _levenshtein.o, but that doesn't seem to help.

I'm sure this is obvious for some people but better instructions are needed.

**Comment by ztane** [comment]
you'd install the package using `pip`: `pip install python-Levenshtein` (would also download and install properly).

**Comment by imadie** [comment]
hi @ztane I know this we should install using pip, but right now I am working in a big cluster where I can't install it, and we don't even have virtualend, or so. My only option is to provide this module aside the scripts I am using, so of course my first try was `import Levenshtein` and then it fails as said with `ImportError: cannot import name _levenshtein` Is there any workaround for this particular case?
Thanks for your help

**Comment by bigsmiles** [comment]
I met the same problem! how do you solve it ?

**Comment by ztane** [comment]
@bigsmiles you need to install it with its `setup.py`. If you cannot install it with `pip` from `pypi`, then build a reusable wheel for your architecture and then install that with `pip`. Unfortunately, I don't have much time to provide a precompiled wheel except perhaps I could consider supporting Linux with manylinux image.
