### ISSUE TITLE
Error - Conda Build Final Step - Windows x64

### ISSUE THREAD

**Issue by bmcguirk** [ztane/python-Levenshtein#24]
Hi guys -

After laboriously installing Microsoft dev tools, I got this error on the very last step: 
```
===== testing package: python-levenshtein-0.12.0-py34_0 =====
import: 'Levenshtein'
Traceback (most recent call last):
  File "C:\Anaconda3\conda-bld\test-tmp_dir\run_test.py", line 25, in <module>
    import Levenshtein
  File "C:\Anaconda3\envs\_test\lib\site-packages\python_Levenshtein-0.12.0-py3.
4-win-amd64.egg\Levenshtein\__init__.py", line 1, in <module>
    from Levenshtein import _levenshtein
ImportError: DLL load failed: The specified module could not be found.
TESTS FAILED: python-levenshtein-0.12.0-py34_0
```

Any thoughts? It did look like it compiled successfully prior to this step.

**Comment by ztane** [comment]
Can you paste the full log prior to that, and check if the `.dll` file was generated.

**Comment by bmcguirk** [comment]
Ok, tried this again. Here you go:

PS C:\Anaconda3\pkg_assembly> conda skeleton pypi python-levenshtein
    python-levenshtein not found, trying python-Levenshtein
    Warning, the following versions were found for python-Levenshtein
    0.12.0
    0.11.2
    0.11.1
    0.10.2
    0.10.1
    Using 0.12.0
    Use --version to specify a different version.
    Using url https://pypi.python.org/packages/source/p/python-Levenshtein/python-Levenshtein-0.12.0.tar.gz (47 KB) for pyth
    on-Levenshtein.
    Downloading python-Levenshtein
    Using cached download
    Unpacking python-Levenshtein...
    done
    working in C:\Users\BRIAN~1.MCG\AppData\Local\Temp\tmp3iuy1q5dconda_skeleton_python-Levenshtein-0.12.0.tar.gz
    Fetching package metadata: ......
    Solving package specifications: .
    The following packages will be downloaded:

        package                    |            build
        ---------------------------|-----------------
        setuptools-18.3.2          |           py34_0         651 KB
        wheel-0.26.0               |           py34_1         118 KB
        ------------------------------------------------------------
                                               Total:         770 KB

    The following NEW packages will be INSTALLED:

        numpy:      1.9.3-py34_0
        pip:        7.1.2-py34_0
        python:     3.4.3-0
        pyyaml:     3.11-py34_2
        setuptools: 18.3.2-py34_0
        wheel:      0.26.0-py34_1

    Fetching packages ...
    setuptools-18. 100% |###############################| Time: 0:00:00   2.02 MB/s
    wheel-0.26.0-p 100% |###############################| Time: 0:00:00 355.46 kB/s
    Extracting packages ...
    [      COMPLETE      ]|##################################################| 100%
    Linking packages ...
    [      COMPLETE      ]|##################################################| 100%
    Applying patch: 'C:\\Users\\BRIAN~1.MCG\\AppData\\Local\\Temp\\tmp3iuy1q5dconda_skeleton_python-Levenshtein-0.12.0.tar.g
    z\\pypi-distutils.patch'
    patching file `core.py'
    Hunk #1 succeeded at 168 with fuzz 2 (offset 1 line).
    Writing recipe for python-levenshtein
    Done
    PS C:\Anaconda3\pkg_assembly> conda build python-levenshtein
    Removing old build environment
    Removing old work directory
    BUILD START: python-levenshtein-0.12.0-py34_0
    Fetching package metadata: ......
    Solving package specifications: .
    The following NEW packages will be INSTALLED:

        pip:        7.1.2-py34_0
        python:     3.4.3-0
        setuptools: 18.3.2-py34_0
        wheel:      0.26.0-py34_1

    Linking packages ...
    [      COMPLETE      ]|##################################################| 100%
    Removing old work directory
    Source cache directory is: C:\Anaconda3\conda-bld\src_cache
    Found source in cache: python-Levenshtein-0.12.0.tar.gz
    Extracting download
    Package: python-levenshtein-0.12.0-py34_0
    source tree in: C:\Anaconda3\conda-bld\work\python-Levenshtein-0.12.0

    C:\Anaconda3\conda-bld\work\python-Levenshtein-0.12.0>call "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\vcvar
    sall.bat" amd64
    The specified configuration type is missing.  The tools for the
    configuration might not be installed.

    C:\Anaconda3\conda-bld\work\python-Levenshtein-0.12.0>REM ===== end generated header =====

    C:\Anaconda3\conda-bld\work\python-Levenshtein-0.12.0>"C:\Anaconda3\envs\_build\python.exe" setup.py install
    running install
    running bdist_egg
    running egg_info
    writing top-level names to python_Levenshtein.egg-info\top_level.txt
    writing python_Levenshtein.egg-info\PKG-INFO
    writing requirements to python_Levenshtein.egg-info\requires.txt
    writing entry points to python_Levenshtein.egg-info\entry_points.txt
    writing dependency_links to python_Levenshtein.egg-info\dependency_links.txt
    writing namespace_packages to python_Levenshtein.egg-info\namespace_packages.txt
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files matching '*pyc' found anywhere in distribution
    warning: no previously-included files matching '*so' found anywhere in distribution
    warning: no previously-included files matching '.project' found anywhere in distribution
    warning: no previously-included files matching '.pydevproject' found anywhere in distribution
    writing manifest file 'python_Levenshtein.egg-info\SOURCES.txt'
    installing library code to build\bdist.win-amd64\egg
    running install_lib
    running build_py
    creating build
    creating build\lib.win-amd64-3.4
    creating build\lib.win-amd64-3.4\Levenshtein
    copying Levenshtein\StringMatcher.py -> build\lib.win-amd64-3.4\Levenshtein
    copying Levenshtein\__init__.py -> build\lib.win-amd64-3.4\Levenshtein
    copying Levenshtein\_levenshtein.c -> build\lib.win-amd64-3.4\Levenshtein
    copying Levenshtein\_levenshtein.h -> build\lib.win-amd64-3.4\Levenshtein
    running build_ext
    building 'Levenshtein._levenshtein' extension
    Traceback (most recent call last):
      File "setup.py", line 46, in <module>
        """,
      File "C:\Anaconda3\envs\_build\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Anaconda3\envs\_build\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "C:\Anaconda3\envs\_build\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Anaconda3\envs\_build\lib\site-packages\setuptools-18.3.2-py3.4.egg\setuptools\command\install.py", line 67,
    in run
      File "C:\Anaconda3\envs\_build\lib\site-packages\setuptools-18.3.2-py3.4.egg\setuptools\command\install.py", line 109,
     in do_egg_install
      File "C:\Anaconda3\envs\_build\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Anaconda3\envs\_build\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Anaconda3\envs\_build\lib\site-packages\setuptools-18.3.2-py3.4.egg\setuptools\command\bdist_egg.py", line 16
    0, in run
      File "C:\Anaconda3\envs\_build\lib\site-packages\setuptools-18.3.2-py3.4.egg\setuptools\command\bdist_egg.py", line 14
      6, in call_command
      File "C:\Anaconda3\envs\_build\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Anaconda3\envs\_build\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Anaconda3\envs\_build\lib\site-packages\setuptools-18.3.2-py3.4.egg\setuptools\command\install_lib.py", line
    10, in run
      File "C:\Anaconda3\envs\_build\lib\distutils\command\install_lib.py", line 107, in build
        self.run_command('build_ext')
      File "C:\Anaconda3\envs\_build\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Anaconda3\envs\_build\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Anaconda3\envs\_build\lib\site-packages\setuptools-18.3.2-py3.4.egg\setuptools\command\build_ext.py", line 49
    , in run
      File "C:\Anaconda3\envs\_build\lib\distutils\command\build_ext.py", line 339, in run
        self.build_extensions()
      File "C:\Anaconda3\envs\_build\lib\distutils\command\build_ext.py", line 448, in build_extensions
        self.build_extension(ext)
      File "C:\Anaconda3\envs\_build\lib\site-packages\setuptools-18.3.2-py3.4.egg\setuptools\command\build_ext.py", line 17
    4, in build_extension
      File "C:\Anaconda3\envs\_build\lib\distutils\command\build_ext.py", line 503, in build_extension
        depends=ext.depends)
      File "C:\Anaconda3\envs\_build\lib\distutils\msvc9compiler.py", line 460, in compile
        self.initialize()
      File "C:\Anaconda3\envs\_build\lib\distutils\msvc9compiler.py", line 371, in initialize
        vc_env = query_vcvarsall(VERSION, plat_spec)
      File "C:\Anaconda3\envs\_build\lib\site-packages\setuptools-18.3.2-py3.4.egg\setuptools\msvc9_support.py", line 52, in
     query_vcvarsall
      File "C:\Anaconda3\envs\_build\lib\distutils\msvc9compiler.py", line 287, in query_vcvarsall
        raise ValueError(str(list(result.keys())))
    ValueError: ['path']

    C:\Anaconda3\conda-bld\work\python-Levenshtein-0.12.0>if errorlevel 1 exit 1
    Command failed: C:\Windows\system32\cmd.exe /c call bld.bat

Reasonably certain is has to do with requiring 64bit Windows SDK, etc.

**Comment by bmcguirk** [comment]
@ztane Any thoughts on this? Would love to get this installed properly.

**Comment by ztane** [comment]
Sorry, I am not developing on Windows. In any case, this seems not to be specific to Levenshtein; see for example http://stackoverflow.com/questions/13596407/errors-while-building-installing-c-module-for-python-2-7
